### ISSUE TITLE
Python 3.7 support

### ISSUE THREAD

**Issue by VelizarVESSELINOV** [GoogleCloudPlatform/getting-started-python#168]
The current version depends on https://github.com/GoogleCloudPlatform/psq that is incompatible with Python 3.7.
Please remove dependency to psq or upgrade psq.

**Comment by engelke** [comment]
Thank you for your report. Sorry to be so late to respond, but the problem was fixed not long after this report. Please let us know if there's still a problem.

**Comment by VelizarVESSELINOV** [comment]
@engelke yes still have the problem:
```
  File "/Users/vv/Documents/AzureDevOps/WCLApp/dpdp/task.py", line 4, in <module>
    from psq import Queue
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/psq/__init__.py", line 24, in <module>
    from .broadcast_queue import BroadcastQueue
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/psq/broadcast_queue.py", line 20, in <module>
    from . import queue
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/psq/queue.py", line 37
    name='default', storage=None, extra_context=None, async=True):
                                                          ^
SyntaxError: invalid syntax
```

The psq code is fixed (for Python 3.7) but still no new release of psq with the fix (from last year).

**Comment by yomikoye** [comment]
Hi everyone!
I'd appreciate some pointers on how you solved this problem @VelizarVESSELINOV. I see "async" is now a reserved word in python so I changed modified the variable name which cleared that problem. However, I am having issues with the other dependencies as well. Is there any way to confirm which python version was used for the project as it was not included in the requirements.txt file? 

For example, the latest error is this:
`(py-bookshelf-env) C:\Users\k\Google\Cloud SDK\getting-started-python\7-gce>python main.py
Traceback (most recent call last):
  File "main.py", line 28, in <module>
    books_queue = bookshelf.tasks.get_books_queue()
  File "C:\Users\k\Google\Cloud SDK\getting-started-python\7-gce\bookshelf\tasks.py", line 35, in get_books_queue
    return psq.Queue(
  File "C:\Users\k\Google\Cloud SDK\getting-started-python\7-gce\py-bookshelf-env\lib\site-packages\psq\queue.py", line 45, in __init__
    self.topic_path = self._get_or_create_topic()
  File "C:\Users\k\Google\Cloud SDK\getting-started-python\7-gce\py-bookshelf-env\lib\site-packages\psq\queue.py", line 59, in _get_or_create_topic
    self.publisher_client.get_topic(topic_path)
  File "C:\Users\k\Google\Cloud SDK\getting-started-python\7-gce\py-bookshelf-env\lib\site-packages\google\cloud\pubsub_v1\_gapic.py", line 40, in <lambda>
    fx = lambda self, *a, **kw: wrapped_fx(self.api, *a, **kw)  # noqa
  File "C:\Users\k\Google\Cloud SDK\getting-started-python\7-gce\py-bookshelf-env\lib\site-packages\google\pubsub_v1\services\publisher\client.py", line 621, in get_topic
    request = pubsub.GetTopicRequest(request)
  File "C:\Users\k\Google\Cloud SDK\getting-started-python\7-gce\py-bookshelf-env\lib\site-packages\proto\message.py", line 446, in __init__
    raise TypeError(
TypeError: Invalid constructor input for GetTopicRequest: 'projects/python-bookshelf-303717/topics/psq-books'
Waiting up to 5 seconds.
Sent all pending logs.`

**Comment by NexturnZ** [comment]
@yomikoye Hi, I just saw exactly the same problem. Have you figured it out? Thank you!
