### ISSUE TITLE
Cannot upload image

### ISSUE THREAD

**Issue by jackchi** [GoogleCloudPlatform/getting-started-python#266]
Hello there, 

I'm following the Getting Started -> bookshelf App and I made sure that I have setup the Pre-reqs like - configuring billing, creating app engine, creating a Firestore, the app is running both deployed and in development mode but is there some API being out of date here?
https://gothic-span-272921.uc.r.appspot.com/

```python
2020-05-25 04:04:19 default[20200524t205909]  Traceback (most recent call last):    File "/env/lib/python3.7/site-packages/flask/app.py", line 2447, in wsgi_app      response = self.full_dispatch_reques
t()    File "/env/lib/python3.7/site-packages/flask/app.py", line 1952, in full_dispatch_request      rv = self.handle_user_exception(e)    File "/env/lib/python3.7/site-packages/flask/app.py", line 182
1, in handle_user_exception      reraise(exc_type, exc_value, tb)    File "/env/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise      raise value    File "/env/lib/python3.7/site-packa
ges/flask/app.py", line 1950, in full_dispatch_request      rv = self.dispatch_request()    File "/env/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request      return self.view_fun
ctions[rule.endpoint](**req.view_args)    File "/srv/main.py", line 85, in add      image_url = upload_image_file(request.files.get('image'))    File "/srv/main.py", line 37, in upload_image_file      i
mg.content_type    File "/srv/storage.py", line 65, in upload_file      content_type=content_type)    File "/env/lib/python3.7/site-packages/google/cloud/storage/blob.py", line 1363, in upload_from_stri
ng      predefined_acl=predefined_acl,    File "/env/lib/python3.7/site-packages/google/cloud/storage/blob.py", line 1267, in upload_from_file      _raise_from_invalid_response(exc)    File "/env/lib/py
thon3.7/site-packages/google/cloud/storage/blob.py", line 2156, in _raise_from_invalid_response      raise exceptions.from_http_status(response.status_code, message, response=response)  google.api_core.
exceptions.NotFound: 404 POST https://storage.googleapis.com/upload/storage/v1/b/gothic-span-272921_bucket/o?uploadType=multipart: ('Request failed with status code', 404, 'Expected one of', <HTTPStatus
.OK: 200>)
```

**Comment by jackchi** [comment]
Nevermind. The tutorial first doesn't allow you to upload the image.
