### ISSUE TITLE
cannot run main.py in 7-gce: HttpAccessTokenRefreshError: No JSON object could be decoded

### ISSUE THREAD

**Issue by steren** [GoogleCloudPlatform/getting-started-python#38]
I follow the instructions on https://cloud.google.com/python/getting-started/run-on-compute-engine
(+ added my client ID and client secret)

(env) steren@steren-tests-error-gce:~/getting-started-python/7-gce$ python main.py
INFO:oauth2client.client:Attempting refresh to obtain initial access_token
Traceback (most recent call last):
  File "main.py", line 28, in <module>
    books_queue = bookshelf.tasks.get_books_queue()
  File "/home/steren/getting-started-python/7-gce/bookshelf/tasks.py", line 33, in get_books_queue
    client, 'books', extra_context=current_app.app_context)
  File "/home/steren/getting-started-python/7-gce/env/local/lib/python2.7/site-packages/psq/queue.py", line 40, in __init__
    self.topic = self._get_or_create_topic()
  File "/home/steren/getting-started-python/7-gce/env/local/lib/python2.7/site-packages/psq/queue.py", line 50, in _get_or_create_topic
    if not topic.exists():
  File "/home/steren/getting-started-python/7-gce/env/local/lib/python2.7/site-packages/gcloud/pubsub/topic.py", line 144, in exists
    client.connection.api_request(method='GET', path=self.path)
  File "/home/steren/getting-started-python/7-gce/env/local/lib/python2.7/site-packages/gcloud/connection.py", line 335, in api_request
    target_object=_target_object)
  File "/home/steren/getting-started-python/7-gce/env/local/lib/python2.7/site-packages/gcloud/connection.py", line 236, in _make_request
    return self._do_request(method, url, headers, data, target_object)
  File "/home/steren/getting-started-python/7-gce/env/local/lib/python2.7/site-packages/gcloud/connection.py", line 265, in _do_request
    body=data)
  File "/home/steren/getting-started-python/7-gce/env/local/lib/python2.7/site-packages/oauth2client/client.py", line 572, in new_request
    self._refresh(request_orig)
  File "/home/steren/getting-started-python/7-gce/env/local/lib/python2.7/site-packages/oauth2client/gce.py", line 94, in _refresh
    status=response.status)
oauth2client.client.HttpAccessTokenRefreshError: No JSON object could be decoded

**Comment by waprin** [comment]
Thank you for reporting your issue. We are a bit busy this week with GCP Next but I'l try to investigate your problem as soon as possible

**Comment by jonparrott** [comment]
Can you confirm which version of oauth2client is installed?

**Comment by steren** [comment]
I use the one in requirements.txt: oauth2client==1.5.2

I am not sure how to verify it.
I see this folder: env/lib/python2.7/site-packages/oauth2client/oauth2client-1.5.2.dist-info

so I guess it is 1.5.2

**Comment by jonparrott** [comment]
Yeah, there's a bug in 1.5.2 that prevents GCE credentials from working. We're working on a large update to this that should fix that, but you should be able to just update oauth2client and google-api-python-client to the latest versions and it should work.

**Comment by steren** [comment]
I will try this.
I think it's rather urgent for you to update the example, because the tutorial is currently broken.

**Comment by jonparrott** [comment]
We're working on it, see PR #37.

**Comment by steren** [comment]
updating to the latest version introduces another error:
    from oauth2client.flask_util import UserOAuth2
ImportError: No module named flask_util

I also needed to change in __init__.py: 
from oauth2client.contrib.flask_util import UserOAuth2

**Comment by jonparrott** [comment]
Cool, does everything work from there?

**Comment by steren** [comment]
Yes. I could make it run on a GCE instance.
Thanks
