### ISSUE TITLE
More Button still doesn't work

### ISSUE THREAD

**Issue by medyagh** [GoogleCloudPlatform/getting-started-python#55]
I opened this issue it has been marked as solved, I just deleted everything and pulled the project. and I still get this error in both local and live .
```
gcloud.exceptions.BadRequest
gcloud.exceptions.BadRequest: 400 com.google.protobuf.InvalidProtocolBufferException: Error parsing protocol message

Traceback (most recent call last)
File "/home/medya/.local/lib/python3.4/site-packages/flask/app.py", line 1836, in __call__
return self.wsgi_app(environ, start_response)
File "/home/medya/.local/lib/python3.4/site-packages/flask/app.py", line 1820, in wsgi_app
response = self.make_response(self.handle_exception(e))
File "/home/medya/.local/lib/python3.4/site-packages/flask/app.py", line 1403, in handle_exception
reraise(exc_type, exc_value, tb)
File "/home/medya/.local/lib/python3.4/site-packages/flask/_compat.py", line 33, in reraise
raise value
File "/home/medya/.local/lib/python3.4/site-packages/flask/app.py", line 1817, in wsgi_app
response = self.full_dispatch_request()
File "/home/medya/.local/lib/python3.4/site-packages/flask/app.py", line 1477, in full_dispatch_request
rv = self.handle_user_exception(e)
File "/home/medya/.local/lib/python3.4/site-packages/flask/app.py", line 1381, in handle_user_exception
reraise(exc_type, exc_value, tb)
File "/home/medya/.local/lib/python3.4/site-packages/flask/_compat.py", line 33, in reraise
raise value
File "/home/medya/.local/lib/python3.4/site-packages/flask/app.py", line 1475, in full_dispatch_request
rv = self.dispatch_request()
File "/home/medya/.local/lib/python3.4/site-packages/flask/app.py", line 1461, in dispatch_request
return self.view_functions[rule.endpoint](**req.view_args)
File "/home/medya/workspace/getting-started-python/2-structured-data/bookshelf/crud.py", line 29, in list
books, next_page_token = get_model().list(cursor=token)
File "/home/medya/workspace/getting-started-python/2-structured-data/bookshelf/model_datastore.py", line 56, in list
entities, more_results, cursor = it.next_page()
File "/home/medya/.local/lib/python3.4/site-packages/gcloud/datastore/query.py", line 424, in next_page
transaction_id=transaction and transaction.id,
File "/home/medya/.local/lib/python3.4/site-packages/gcloud/datastore/connection.py", line 271, in run_query
_datastore_pb2.RunQueryResponse)
File "/home/medya/.local/lib/python3.4/site-packages/gcloud/datastore/connection.py", line 117, in _rpc
data=request_pb.SerializeToString())
File "/home/medya/.local/lib/python3.4/site-packages/gcloud/datastore/connection.py", line 94, in _request
raise make_exception(headers, error_status.message, use_json=False)
gcloud.exceptions.BadRequest: 400 com.google.protobuf.InvalidProtocolBufferException: Error parsing protocol message
The debugger caught an exception in your WSGI application. You can now look at the traceback which led to the error.
To switch between the interactive traceback and the plaintext one, you can click on the "Traceback" headline. From the text traceback you can also create a paste of it. For code execution mouse-over the frame you want to debug and click on the console icon on the right side.

You can execute arbitrary Python code in the stack frames and there are some extra helpers available for introspection:

dump() shows all variables in the frame
dump(obj) dumps all that's known about the object
Brought to you by DON'T PANIC, your friendly Werkzeug powered traceback interpreter.
```

and if you add more books, it will give you this error:

```
binascii.Error
binascii.Error: Incorrect padding

Traceback (most recent call last)
File "/home/medya/.local/lib/python3.4/site-packages/flask/app.py", line 1836, in __call__
return self.wsgi_app(environ, start_response)
File "/home/medya/.local/lib/python3.4/site-packages/flask/app.py", line 1820, in wsgi_app
response = self.make_response(self.handle_exception(e))
File "/home/medya/.local/lib/python3.4/site-packages/flask/app.py", line 1403, in handle_exception
reraise(exc_type, exc_value, tb)
File "/home/medya/.local/lib/python3.4/site-packages/flask/_compat.py", line 33, in reraise
raise value
File "/home/medya/.local/lib/python3.4/site-packages/flask/app.py", line 1817, in wsgi_app
response = self.full_dispatch_request()
File "/home/medya/.local/lib/python3.4/site-packages/flask/app.py", line 1477, in full_dispatch_request
rv = self.handle_user_exception(e)
File "/home/medya/.local/lib/python3.4/site-packages/flask/app.py", line 1381, in handle_user_exception
reraise(exc_type, exc_value, tb)
File "/home/medya/.local/lib/python3.4/site-packages/flask/_compat.py", line 33, in reraise
raise value
File "/home/medya/.local/lib/python3.4/site-packages/flask/app.py", line 1475, in full_dispatch_request
rv = self.dispatch_request()
File "/home/medya/.local/lib/python3.4/site-packages/flask/app.py", line 1461, in dispatch_request
return self.view_functions[rule.endpoint](**req.view_args)
File "/home/medya/workspace/getting-started-python/2-structured-data/bookshelf/crud.py", line 29, in list
books, next_page_token = get_model().list(cursor=token)
File "/home/medya/workspace/getting-started-python/2-structured-data/bookshelf/model_datastore.py", line 56, in list
entities, more_results, cursor = it.next_page()
File "/home/medya/.local/lib/python3.4/site-packages/gcloud/datastore/query.py", line 407, in next_page
pb.start_cursor = base64.urlsafe_b64decode(start_cursor)
File "/usr/lib/python3.4/base64.py", line 135, in urlsafe_b64decode
return b64decode(s)
File "/usr/lib/python3.4/base64.py", line 90, in b64decode
return binascii.a2b_base64(s)
binascii.Error: Incorrect padding
The debugger caught an exception in your WSGI application. You can now look at the traceback which led to the error.
To switch between the interactive traceback and the plaintext one, you can click on the "Traceback" headline. From the text traceback you can also create a paste of it. For code execution mouse-over the frame you want to debug and click on the console icon on the right side.

You can execute arbitrary Python code in the stack frames and there are some extra helpers available for introspection:

dump() shows all variables in the frame
dump(obj) dumps all that's known about the object

```

**Comment by jonparrott** [comment]
Thanks for reporting this, I'll investigate shortly.

**Comment by medyagh** [comment]
no problem btw I am trying with python3 as the app.yaml suggests I noticed I dont get error with python2 and also for python2 there is no Back button or previous page button.
