### ISSUE TITLE
gcloud.exceptions.Forbidden when attempting to access app @ localhost:8080

### ISSUE THREAD

**Issue by thundergolfer** [GoogleCloudPlatform/getting-started-python#66]
I have followed all of the instructions in [this tutorial](https://cloud.google.com/python/getting-started/using-cloud-datastore?authuser=0#before-you-begin) for running the Bookshelf app with NoSQL.

Getting to the end and attempting to access `http://localhost:8080`, I get a `gcloud.exceptions.Forbidden` exception. 

Here is the traceback

`Traceback (most recent call last):
  File "C:\Users\Jonathon\Documents\GitHub\getting-started-python\2-structured-data\env\lib\site-packages\flask\app.py", line 1836, in __call__
    return self.wsgi_app(environ, start_response)
  File "C:\Users\Jonathon\Documents\GitHub\getting-started-python\2-structured-data\env\lib\site-packages\flask\app.py", line 1820, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "C:\Users\Jonathon\Documents\GitHub\getting-started-python\2-structured-data\env\lib\site-packages\flask\app.py", line 1403, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\Jonathon\Documents\GitHub\getting-started-python\2-structured-data\env\lib\site-packages\flask\_compat.py", line 33, in reraise
    raise value
  File "C:\Users\Jonathon\Documents\GitHub\getting-started-python\2-structured-data\env\lib\site-packages\flask\app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Jonathon\Documents\GitHub\getting-started-python\2-structured-data\env\lib\site-packages\flask\app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\Jonathon\Documents\GitHub\getting-started-python\2-structured-data\env\lib\site-packages\flask\app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\Jonathon\Documents\GitHub\getting-started-python\2-structured-data\env\lib\site-packages\flask\_compat.py", line 33, in reraise
    raise value
  File "C:\Users\Jonathon\Documents\GitHub\getting-started-python\2-structured-data\env\lib\site-packages\flask\app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Jonathon\Documents\GitHub\getting-started-python\2-structured-data\env\lib\site-packages\flask\app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\Jonathon\Documents\GitHub\getting-started-python\2-structured-data\bookshelf\crud.py", line 29, in list
    books, next_page_token = get_model().list(cursor=token)
  File "C:\Users\Jonathon\Documents\GitHub\getting-started-python\2-structured-data\bookshelf\model_datastore.py", line 56, in list
    entities, more_results, cursor = it.next_page()
  File "C:\Users\Jonathon\Documents\GitHub\getting-started-python\2-structured-data\env\lib\site-packages\gcloud\datastore\query.py", line 424, in next_page
    transaction_id=transaction and transaction.id,
  File "C:\Users\Jonathon\Documents\GitHub\getting-started-python\2-structured-data\env\lib\site-packages\gcloud\datastore\connection.py", line 275, in run_query
    _datastore_pb2.RunQueryResponse)
  File "C:\Users\Jonathon\Documents\GitHub\getting-started-python\2-structured-data\env\lib\site-packages\gcloud\datastore\connection.py", line 121, in _rpc
    data=request_pb.SerializeToString())
  File "C:\Users\Jonathon\Documents\GitHub\getting-started-python\2-structured-data\env\lib\site-packages\gcloud\datastore\connection.py", line 98, in _request
    raise make_exception(headers, error_status.message, use_json=False)
gcloud.exceptions.Forbidden: 403 Not authorized.`

**Comment by jonparrott** [comment]
Hi @thundergolfer, can you verify the following;

- The Google Cloud Datastore API is enabled for your project. You can check this in the APIs section on https://cloud.google.com
- That you've run `gcloud auth login` or `gcloud init`.

**Comment by jonparrott** [comment]
I'm closing this issue due to inactivity. Please feel free to comment and I'll re-open.
