### ISSUE TITLE
pubsub gcloud example not working: ImportError: No module named pkg_resource

### ISSUE THREAD

**Issue by MeLight** [GoogleCloudPlatform/getting-started-python#71]
Downloaded the gcloud lib, imported it. Very sad.

 (/base/data/home/runtimes/python27/python27_lib/versions/1/google/appengine/runtime/wsgi.py:263)
Traceback (most recent call last):
  File "/base/data/home/runtimes/python27/python27_lib/versions/1/google/appengine/runtime/wsgi.py", line 240, in Handle
    handler = _config_handle.add_wsgi_middleware(self._LoadHandler())
  File "/base/data/home/runtimes/python27/python27_lib/versions/1/google/appengine/runtime/wsgi.py", line 299, in _LoadHandler
    handler, path, err = LoadObject(self._handler)
  File "/base/data/home/runtimes/python27/python27_lib/versions/1/google/appengine/runtime/wsgi.py", line 96, in LoadObject
    __import__(cumulative_path)
  File "/base/data/home/apps/s~bucket-bot-1/1.394392579757390208/api/oauth/slack.py", line 8, in <module>
    from lib.gcloud import pubsub
  File "/base/data/home/apps/s~bucket-bot-1/1.394392579757390208/lib/gcloud/__init__.py", line 17, in <module>
    from pkg_resources import get_distribution
ImportError: No module named pkg_resources

**Comment by MeLight** [comment]
My bad, didnt vendor the gcloud lib
