### ISSUE TITLE
Error when clicking "more" and having exactly 10 books.

### ISSUE THREAD

**Issue by shun-fan** [GoogleCloudPlatform/getting-started-python#8]
Deploy part 2 - using datastore > visit /books > click "more" > Internal server error

**Comment by jonparrott** [comment]
Can you send over any stacktrace? Does this occur locally?

**Comment by shun-fan** [comment]
Seems to happen locally as well.

127.0.0.1 - - [12/Oct/2015 13:18:27] "GET /books/?page_token=CkUKEwoFdGl0bGUSChoIdGhlb2RvcmUSKmoVc35iaWd0YWJsZS1zZmFuLXRlc3QxchELEgRCb29rGICAgIC+goMKDBgAIAA= HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/Users/sfan/.homebrew/lib/python2.7/site-packages/flask/app.py", line 1836, in __call__
    return self.wsgi_app(environ, start_response)
  File "/Users/sfan/.homebrew/lib/python2.7/site-packages/flask/app.py", line 1820, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/Users/sfan/.homebrew/lib/python2.7/site-packages/flask/app.py", line 1403, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/sfan/.homebrew/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/sfan/.homebrew/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/sfan/.homebrew/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/sfan/.homebrew/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/sfan/.homebrew/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/sfan/test/2-structured-data/bookshelf/crud.py", line 26, in list
    books, next_page_token = get_model().list(cursor=token)
  File "/Users/sfan/test/2-structured-data/bookshelf/model_datastore.py", line 57, in list
    entities, more_results, cursor = it.next_page()
  File "/Library/Python/2.7/site-packages/gcloud/datastore/query.py", line 391, in next_page
    pb.start_cursor = base64.b64decode(start_cursor)
  File "/Users/sfan/.homebrew/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/base64.py", line 76, in b64decode
    # Transform this exception for consistency
TypeError: Incorrect padding

**Comment by jonparrott** [comment]
Thanks! Will investigate.

**Comment by shun-fan** [comment]
https://github.com/GoogleCloudPlatform/getting-started-python/blob/master/bookshelf/model_datastore.py#L56 
I think it has to do with this line. You return a token if there are 10 books, but if there are exactly 10 books, it will try to load an additional page when there aren't any more books. 
Seems like there should be the same issue in the cloudsql backend.

**Comment by jonparrott** [comment]
@dhermes sigh, cursors aren't encoded with the urlsafe base64 encoding. Is there any reason for this? Should user apps just explicitly translate to urlsafe or do you feel like this should be fixed in gcloud-python?

**Comment by dhermes** [comment]
Here's your ~~sign~~ line:
https://github.com/GoogleCloudPlatform/gcloud-python/blob/7e999cfb0af59712a4106c51b63325b5b63addaa/gcloud/datastore/query.py#L424

**Comment by dhermes** [comment]
I don't have an opinion on urlsafe vs. regular b64. Maybe someone else does?

**Comment by jonparrott** [comment]
I have a pretty strong opinion that we should use urlsafe, especially given the context that a cursor is very often passed around via URLs or forms.

Also, ndb's cursors [objects that serialize to urlsafe b64](https://cloud.google.com/appengine/docs/python/ndb/queries#cursors), so pleaseeeeee? :D

**Comment by dhermes** [comment]
I'm super busy for the next 7-10 days. Care to send a PR (I can code review from my phone on public transit, can't write code though)?

**Comment by jonparrott** [comment]
Absolutely. Thanks!

**Comment by dhermes** [comment]
:+1: Thank YOU Jon

**Comment by jonparrott** [comment]
Closing this, as it should be fixed upstream.
