### ISSUE TITLE
can't loggin

### ISSUE THREAD

**Issue by askshjcn** [GoogleCloudPlatform/getting-started-python#95]
I deploy app 3-binary-data and it work great.when i deploy 4-auth app and click My Books,I login with my google account,it appears:

An internal error occurred:
'profile'
See logs for full stacktrace.

2016-11-04 07:33:57 default[20161103t052819]    File "/home/vmagent/app/bookshelf/crud.py", line 66, in list_mine
2016-11-04 07:33:57 default[20161103t052819]      user_id=session['profile']['id'],
2016-11-04 07:33:57 default[20161103t052819]    File "/env/lib/python3.4/site-packages/werkzeug/local.py", line 373, in <lambda>
2016-11-04 07:33:57 default[20161103t052819]      __getitem__ = lambda x, i: x._get_current_object()[i]
2016-11-04 07:33:57 default[20161103t052819]  KeyError: 'profile'

Any idea?

**Comment by jonparrott** [comment]
interesting. Can you print out the session and see what's in there? (Please to elide any personally-identifiable information)

**Comment by askshjcn** [comment]
2016-11-08 03:14:54 default[20161103t052819]  2016/11/08 03:14:54 Got a connection for "gapps-lianxiren:asia-east1:mjsql"
2016-11-08 03:17:12 default[20161103t052819]  INFO:oauth2client.client:Received token response with no refresh_token. Consider reauthenticating with prompt='consent'.
2016-11-08 03:17:12 default[20161103t052819]  INFO:oauth2client.client:Successfully retrieved access token
2016-11-08 03:17:12 default[20161103t052819]  [2016-11-08 03:17:12,438] ERROR in __init__: Error while obtaining user profile: {'alt-svc': 'quic=":443"; ma=2592000; v="36,35,34"', 'expires': 'Tue, 08 Nov 2016 03:17:12 GMT', 'content-type': 'application/json; charset=UTF-8', 'x-xss-protection': '1; mode=block', 'date': 'Tue, 08 Nov 2016 03:17:12 GMT', 'content-length': '918', 'x-content-type-options': 'nosniff', 'cache-control': 'private, max-age=0', '-content-encoding': 'gzip', 'x-frame-options': 'SAMEORIGIN', 'transfer-encoding': 'chunked', 'vary': 'Origin, X-Origin', 'status': '403', 'server': 'GSE'}
2016-11-08 03:17:12 default[20161103t052819]  ERROR:bookshelf:Error while obtaining user profile: {'alt-svc': 'quic=":443"; ma=2592000; v="36,35,34"', 'expires': 'Tue, 08 Nov 2016 03:17:12 GMT', 'content-type': 'application/json; charset=UTF-8', 'x-xss-protection': '1; mode=block', 'date': 'Tue, 08 Nov 2016 03:17:12 GMT', 'content-length': '918', 'x-content-type-options': 'nosniff', 'cache-control': 'private, max-age=0', '-content-encoding': 'gzip', 'x-frame-options': 'SAMEORIGIN', 'transfer-encoding': 'chunked', 'vary': 'Origin, X-Origin', 'status': '403', 'server': 'GSE'}
2016-11-08 03:17:23 default[20161103t052819]  [2016-11-08 03:17:23,260] ERROR in app: Exception on /books/mine [GET]
2016-11-08 03:17:23 default[20161103t052819]  Traceback (most recent call last):
2016-11-08 03:17:23 default[20161103t052819]    File "/env/lib/python3.4/site-packages/flask/app.py", line 1988, in wsgi_app
2016-11-08 03:17:23 default[20161103t052819]      response = self.full_dispatch_request()
2016-11-08 03:17:23 default[20161103t052819]    File "/env/lib/python3.4/site-packages/flask/app.py", line 1641, in full_dispatch_request
2016-11-08 03:17:23 default[20161103t052819]      rv = self.handle_user_exception(e)
2016-11-08 03:17:23 default[20161103t052819]    File "/env/lib/python3.4/site-packages/flask/app.py", line 1544, in handle_user_exception
2016-11-08 03:17:23 default[20161103t052819]      reraise(exc_type, exc_value, tb)
2016-11-08 03:17:23 default[20161103t052819]    File "/env/lib/python3.4/site-packages/flask/_compat.py", line 33, in reraise
2016-11-08 03:17:23 default[20161103t052819]      raise value
2016-11-08 03:17:23 default[20161103t052819]    File "/env/lib/python3.4/site-packages/flask/app.py", line 1639, in full_dispatch_request
2016-11-08 03:17:23 default[20161103t052819]      rv = self.dispatch_request()
2016-11-08 03:17:23 default[20161103t052819]    File "/env/lib/python3.4/site-packages/flask/app.py", line 1625, in dispatch_request
2016-11-08 03:17:23 default[20161103t052819]      return self.view_functions[rule.endpoint](**req.view_args)
2016-11-08 03:17:23 default[20161103t052819]    File "/env/lib/python3.4/site-packages/oauth2client/contrib/flask_util.py", line 524, in required_wrapper
2016-11-08 03:17:23 default[20161103t052819]      return wrapped_function(*args, **kwargs)
2016-11-08 03:17:23 default[20161103t052819]    File "/home/vmagent/app/bookshelf/crud.py", line 66, in list_mine
2016-11-08 03:17:23 default[20161103t052819]      user_id=session['profile']['id'],
2016-11-08 03:17:23 default[20161103t052819]    File "/env/lib/python3.4/site-packages/werkzeug/local.py", line 373, in <lambda>
2016-11-08 03:17:23 default[20161103t052819]      __getitem__ = lambda x, i: x._get_current_object()[i]
2016-11-08 03:17:23 default[20161103t052819]  KeyError: 'profile'
2016-11-08 03:17:23 default[20161103t052819]  ERROR:bookshelf:Exception on /books/mine [GET]
2016-11-08 03:17:23 default[20161103t052819]  Traceback (most recent call last):
2016-11-08 03:17:23 default[20161103t052819]    File "/env/lib/python3.4/site-packages/flask/app.py", line 1988, in wsgi_app
2016-11-08 03:17:23 default[20161103t052819]      response = self.full_dispatch_request()
2016-11-08 03:17:23 default[20161103t052819]    File "/env/lib/python3.4/site-packages/flask/app.py", line 1641, in full_dispatch_request
2016-11-08 03:17:23 default[20161103t052819]      rv = self.handle_user_exception(e)
2016-11-08 03:17:23 default[20161103t052819]    File "/env/lib/python3.4/site-packages/flask/app.py", line 1544, in handle_user_exception
2016-11-08 03:17:23 default[20161103t052819]      reraise(exc_type, exc_value, tb)
2016-11-08 03:17:23 default[20161103t052819]    File "/env/lib/python3.4/site-packages/flask/_compat.py", line 33, in reraise
2016-11-08 03:17:23 default[20161103t052819]      raise value
2016-11-08 03:17:23 default[20161103t052819]    File "/env/lib/python3.4/site-packages/flask/app.py", line 1639, in full_dispatch_request
2016-11-08 03:17:23 default[20161103t052819]      rv = self.dispatch_request()
2016-11-08 03:17:23 default[20161103t052819]    File "/env/lib/python3.4/site-packages/flask/app.py", line 1625, in dispatch_request
2016-11-08 03:17:23 default[20161103t052819]      return self.view_functions[rule.endpoint](**req.view_args)
2016-11-08 03:17:23 default[20161103t052819]    File "/env/lib/python3.4/site-packages/oauth2client/contrib/flask_util.py", line 524, in required_wrapper
2016-11-08 03:17:23 default[20161103t052819]      return wrapped_function(*args, **kwargs)
2016-11-08 03:17:23 default[20161103t052819]    File "/home/vmagent/app/bookshelf/crud.py", line 66, in list_mine
2016-11-08 03:17:23 default[20161103t052819]      user_id=session['profile']['id'],
2016-11-08 03:17:23 default[20161103t052819]    File "/env/lib/python3.4/site-packages/werkzeug/local.py", line 373, in <lambda>
2016-11-08 03:17:23 default[20161103t052819]      __getitem__ = lambda x, i: x._get_current_object()[i]
2016-11-08 03:17:23 default[20161103t052819]  KeyError: 'profile'

**Comment by jonparrott** [comment]
@askshjcn thanks for the stacktrace, that's helpful, but it would be more helpful if I can see what's actually in the session. Can you do `logging.info(request.session)` at the beginning of `list_mine`?

**Comment by essramos** [comment]
Hi, I am also having this issue, added `logging.info(request.session)`

Got this error : 

`AttributeError: 'Request' object has no attribute 'session'`
